//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UninstallBlockerInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UninstallBlockerInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   adb.exe is not found.
        ///Please check path of adb.exe. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdbNotFound_Desc {
            get {
                return ResourceManager.GetString("AdbNotFound_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   adb.exe is not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdbNotFound_Inst {
            get {
                return ResourceManager.GetString("AdbNotFound_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to install application.
        ///Please try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApkInstallFailed_Desc {
            get {
                return ResourceManager.GetString("ApkInstallFailed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to install application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApkInstallFailed_Inst {
            get {
                return ResourceManager.GetString("ApkInstallFailed_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not found.
        ///Please check path of .apk file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApkNotFound_Desc {
            get {
                return ResourceManager.GetString("ApkNotFound_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApkNotFound_Inst {
            get {
                return ResourceManager.GetString("ApkNotFound_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Complete_Desc {
            get {
                return ResourceManager.GetString("Complete_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to set to device owner.
        ///First, remove all your accounts from device.
        ///After that, try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceOwnerFailed_Desc {
            get {
                return ResourceManager.GetString("DeviceOwnerFailed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to set to device owner に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceOwnerFailed_Inst {
            get {
                return ResourceManager.GetString("DeviceOwnerFailed_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown error occurred.
        ///Please try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_Desc {
            get {
                return ResourceManager.GetString("Error_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown error occurred に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_Inst {
            get {
                return ResourceManager.GetString("Error_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected devices is too many.
        ///Please check your connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooManyDevice_Desc {
            get {
                return ResourceManager.GetString("TooManyDevice_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected devices is too many に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooManyDevice_Inst {
            get {
                return ResourceManager.GetString("TooManyDevice_Inst", resourceCulture);
            }
        }
    }
}
